#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TASK_FLAGGEMS_TEST_MODE="${FLAGGEMS_TEST_MODE:-}"
CONFIG_FILE="${LOCAL_CI_CONFIG:-${SCRIPT_DIR}/config.env}"
if [[ -f "${CONFIG_FILE}" ]]; then
  # shellcheck disable=SC1090
  source "${CONFIG_FILE}"
fi
if [[ -n "${TASK_FLAGGEMS_TEST_MODE}" ]]; then
  FLAGGEMS_TEST_MODE="${TASK_FLAGGEMS_TEST_MODE}"
fi

sha="${1:?usage: run_in_container.sh <commit-sha> [source-branch]}"
branch_override="${2:-}"
if [[ -n "${branch_override}" ]]; then
  GITEE_BRANCH="${branch_override}"
fi
LOCAL_CI_CONTAINER="${LOCAL_CI_CONTAINER:-triton-anchor-dev}"
CONTAINER_CI_RUNNER_DIR="${CONTAINER_CI_RUNNER_DIR:-/tmp/triton-anchor-local-ci-runner-${sha:0:12}-$$}"
LOCAL_CI_CONTAINER_GITEE_USERNAME="${LOCAL_CI_CONTAINER_GITEE_USERNAME:-${GITEE_READ_USERNAME:-${GITEE_USERNAME:-}}}"
LOCAL_CI_CONTAINER_GITEE_TOKEN="${LOCAL_CI_CONTAINER_GITEE_TOKEN:-${GITEE_READ_TOKEN:-}}"
if [[ -z "${LOCAL_CI_CONTAINER_GITEE_TOKEN}" && "${LOCAL_CI_ALLOW_WRITE_TOKEN_IN_CONTAINER:-0}" == "1" ]]; then
  LOCAL_CI_CONTAINER_GITEE_TOKEN="${GITEE_TOKEN:-}"
fi

pass_env=(
  GITEE_REPO_URL GITEE_BRANCH ANCHOR_DIR WORKSPACE
  GITEE_RESULTS_REPO_URL GITEE_RESULTS_BRANCH LOCAL_CI_BASE_SHA LOCAL_CI_BASE_REF
  BACKEND_PROFILE EXPECTED_TRITON_BACKEND BACKEND_PATH BACKEND_ENVSETUP BACKEND_ENVSETUP_ARGS BACKEND_TEST_COMMAND
  RUN_FLAGGEMS_TESTS FLAGGEMS_CLONE_DIR FLAGGEMS_REF FLAGGEMS_PIP_PACKAGES FLAGGEMS_TEST_MODE FLAGGEMS_SAMPLE_SIZE FLAGGEMS_RANDOM_SEED FLAGGEMS_TEST_OP FLAGGEMS_TEST_COMMAND FLAGGEMS_PYTEST_ARGS FLAGGEMS_IDLE_TIMEOUT_SECONDS FLAGGEMS_TOTAL_TIMEOUT_SECONDS FLAGGEMS_FULL_TIMEOUT_EXTENSION_SECONDS FLAGGEMS_FULL_HARD_TIMEOUT_SECONDS FLAGGEMS_CLEAR_CACHE FLAGGEMS_WHITELIST FLAGGEMS_FULL_LIST FLAGGEMS_SELECTED_FILE INSTALL_FLAGGEMS_PACKAGES
  LLVM_BUILD_DIR PPL_ROOT PACKAGE_TOOL PYTHON_BIN PYTHON_VENV_ACTIVATE SOURCE_ENVSETUP FRONTEND_BUILD_COMMAND LOCAL_CI_ARTIFACT_ROOT
  RUN_COMPILE_BENCHMARK COMPILE_BENCHMARK_KERNELS COMPILE_BENCHMARK_REPEAT COMPILE_BENCHMARK_WARMUP
  COMPILE_BENCHMARK_THRESHOLD COMPILE_BENCHMARK_TIMEOUT MAX_JOBS CMAKE_BUILD_PARALLEL_LEVEL NINJAFLAGS UV_LINK_MODE
  RUN_PASS_PROFILE PASS_PROFILE_KERNELS PASS_PROFILE_REPEAT PASS_PROFILE_WARMUP PASS_PROFILE_THRESHOLD
  PASS_PROFILE_MIN_BASE_MS PASS_PROFILE_MIN_DELTA_MS PASS_PROFILE_TIMEOUT
  RUN_IR_SERIALIZATION_BENCHMARK IR_SERIALIZATION_KERNELS IR_SERIALIZATION_REPEAT IR_SERIALIZATION_WARMUP
  IR_SERIALIZATION_METRICS IR_SERIALIZATION_THRESHOLD IR_SERIALIZATION_MIN_BASE_MS
  IR_SERIALIZATION_MIN_DELTA_MS IR_SERIALIZATION_TIMEOUT
)

docker_args=()
for name in "${pass_env[@]}"; do
  if [[ -n "${!name:-}" ]]; then
    docker_args+=(-e "${name}=${!name}")
  fi
done
if [[ -n "${LOCAL_CI_CONTAINER_GITEE_USERNAME}" ]]; then
  docker_args+=(-e "GITEE_USERNAME=${LOCAL_CI_CONTAINER_GITEE_USERNAME}")
fi
if [[ -n "${LOCAL_CI_CONTAINER_GITEE_TOKEN}" ]]; then
  docker_args+=(-e "GITEE_TOKEN=${LOCAL_CI_CONTAINER_GITEE_TOKEN}")
fi

docker exec "${LOCAL_CI_CONTAINER}" mkdir -p "${CONTAINER_CI_RUNNER_DIR}"
docker cp "${SCRIPT_DIR}/." "${LOCAL_CI_CONTAINER}:${CONTAINER_CI_RUNNER_DIR}/"

docker exec \
  "${docker_args[@]}" \
  -e LOCAL_CI_COMMIT="${sha}" \
  -e LOCAL_CI_RUNNER_DIR="${CONTAINER_CI_RUNNER_DIR}" \
  "${LOCAL_CI_CONTAINER}" \
  bash -lc 'bash "${LOCAL_CI_RUNNER_DIR}/run_delivery_local.sh" "${LOCAL_CI_COMMIT}"'
