"""Versioned contracts and static metadata for out-of-tree backend plugins.

Protocol 1.0, CoreEnvironment, Manifest Schema 1.0, and the import-gated
Registry are available here.  Triton's compiler and runtime driver consume
Registry-selected records through the W9 adapter.
"""

from .errors import (
    BackendPluginCapabilityError,
    BackendPluginCompatibilityError,
    BackendPluginConflictError,
    BackendPluginDiscoveryError,
    BackendPluginError,
    BackendPluginInterfaceError,
    BackendPluginLifecycleError,
    BackendPluginLoadError,
    BackendPluginManifestError,
    BackendPluginProtocolError,
    BackendPluginSelectionError,
)
from .capabilities import (
    CapabilityReport,
    evaluate_capabilities,
    evaluate_plugin_capabilities,
    validate_capabilities,
    validate_plugin_capabilities,
)
from .conflicts import (
    Conflict,
    ConflictKind,
    ConflictReport,
    ConflictSeverity,
    detect_conflicts,
    detect_static_conflicts,
)
from .legacy import LegacyBackendPluginShim
from .environment import (
    CORE_ABI_FINGERPRINT_SCHEMA,
    CoreEnvironment,
    collect_core_environment,
    load_build_info,
    normalize_toolchain_version,
)
from .compatibility import (
    CompatibilityCheck,
    CompatibilityReport,
    validate_backend_plugin,
    validate_triton_requirement,
)
from .native import (
    NativeArtifact,
    NativeInspectionReport,
    inspect_native_artifacts,
)
from .manifest import (
    MANIFEST_FILENAME,
    BackendManifestDocument,
    BackendPluginManifest,
    TritonRequirement,
    load_distribution_manifest,
    load_manifest,
    load_manifest_for_entry_point,
    parse_manifest,
)
from .protocol import (
    BACKEND_PLUGIN_PROTOCOL_VERSION,
    DIAGNOSTICS_FIELD_POLICY,
    BackendPlugin,
    BackendPluginBase,
    PluginCompatibilityStatus,
    PluginIsolationMode,
    PluginLifecycleState,
    PluginSource,
    ProtocolFieldDiagnostic,
    ProtocolFieldPolicy,
    ProtocolFieldResult,
    ProtocolFieldStatus,
    can_transition,
    consume_protocol_field,
    evaluate_protocol_field_removal,
)
from .selection import (
    BACKEND_SELECTOR_ENV,
    SelectionDecision,
    SelectionMethod,
    select_backend,
    select_backend_plugin,
)
from .registry import (
    BackendPluginRecord,
    BackendPluginRegistry,
    backend_plugin_registry,
    get_backend_plugin_registry,
)

__all__ = [
    "BACKEND_PLUGIN_PROTOCOL_VERSION",
    "BACKEND_SELECTOR_ENV",
    "DIAGNOSTICS_FIELD_POLICY",
    "MANIFEST_FILENAME",
    "BackendManifestDocument",
    "BackendPlugin",
    "BackendPluginBase",
    "BackendPluginCapabilityError",
    "BackendPluginCompatibilityError",
    "BackendPluginConflictError",
    "BackendPluginDiscoveryError",
    "BackendPluginError",
    "BackendPluginInterfaceError",
    "BackendPluginLifecycleError",
    "BackendPluginLoadError",
    "BackendPluginManifestError",
    "BackendPluginProtocolError",
    "BackendPluginSelectionError",
    "BackendPluginManifest",
    "BackendPluginRecord",
    "BackendPluginRegistry",
    "CompatibilityCheck",
    "CompatibilityReport",
    "CapabilityReport",
    "Conflict",
    "ConflictKind",
    "ConflictReport",
    "ConflictSeverity",
    "CORE_ABI_FINGERPRINT_SCHEMA",
    "CoreEnvironment",
    "LegacyBackendPluginShim",
    "NativeArtifact",
    "NativeInspectionReport",
    "PluginCompatibilityStatus",
    "PluginIsolationMode",
    "PluginLifecycleState",
    "PluginSource",
    "ProtocolFieldDiagnostic",
    "ProtocolFieldPolicy",
    "ProtocolFieldResult",
    "ProtocolFieldStatus",
    "SelectionDecision",
    "SelectionMethod",
    "TritonRequirement",
    "can_transition",
    "consume_protocol_field",
    "backend_plugin_registry",
    "collect_core_environment",
    "detect_conflicts",
    "detect_static_conflicts",
    "evaluate_capabilities",
    "evaluate_plugin_capabilities",
    "evaluate_protocol_field_removal",
    "load_build_info",
    "load_distribution_manifest",
    "load_manifest",
    "load_manifest_for_entry_point",
    "get_backend_plugin_registry",
    "inspect_native_artifacts",
    "normalize_toolchain_version",
    "parse_manifest",
    "select_backend",
    "select_backend_plugin",
    "validate_backend_plugin",
    "validate_capabilities",
    "validate_plugin_capabilities",
    "validate_triton_requirement",
]
