#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_CI_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TASK_RUN_FLAGGEMS_TESTS="${RUN_FLAGGEMS_TESTS:-}"
TASK_FLAGGEMS_TEST_MODE="${FLAGGEMS_TEST_MODE:-}"
TASK_FRONTEND_BUILD_MODE="${FRONTEND_BUILD_MODE:-}"
TASK_LOCAL_CI_PROFILE_FILE="${LOCAL_CI_PROFILE_FILE:-}"
TASK_LOCAL_CI_PROFILE_NAME="${LOCAL_CI_PROFILE_NAME:-}"
TASK_LOCAL_CI_LLVM_HASH="${LOCAL_CI_LLVM_HASH:-}"
TASK_RUN_BACKEND_STAGES="${RUN_BACKEND_STAGES:-}"
TASK_BACKEND_SKIP_REASON="${BACKEND_SKIP_REASON:-}"
CONFIG_FILE="${LOCAL_CI_CONFIG:-${LOCAL_CI_ROOT}/config.env}"
if [[ -f "${CONFIG_FILE}" ]]; then
  # shellcheck disable=SC1090
  source "${CONFIG_FILE}"
fi
if [[ -n "${TASK_LOCAL_CI_PROFILE_FILE}" ]]; then
  resolved_profile="$(
    python3 "${LOCAL_CI_ROOT}/shared/resolve_ci_profile.py" \
      --profile-dir "${LOCAL_CI_PROFILE_DIR:-}" \
      --llvm-hash "${TASK_LOCAL_CI_LLVM_HASH}"
  )"
  if [[ "${resolved_profile}" != "${TASK_LOCAL_CI_PROFILE_FILE}" ]]; then
    echo "Selected Local CI profile changed before deterministic execution." >&2
    exit 2
  fi
  # Backend settings belong to the selected profile. Clear values loaded from
  # the global config so a non-Sophgo profile cannot inherit Sophgo defaults.
  BACKEND_PROFILE=""
  EXPECTED_TRITON_BACKEND=""
  BACKEND_PATH=""
  BACKEND_ENVSETUP=""
  BACKEND_ENVSETUP_ARGS=""
  BACKEND_TEST_COMMAND=""
  BACKEND_UNINSTALL_PACKAGES=""
  BACKEND_WHEEL_PATTERN=""
  # Profile files live outside the task checkout and are controlled by the server.
  # shellcheck disable=SC1090
  source "${resolved_profile}"
fi
LOCAL_CI_PROFILE_FILE="${TASK_LOCAL_CI_PROFILE_FILE}"
LOCAL_CI_PROFILE_NAME="${TASK_LOCAL_CI_PROFILE_NAME}"
LOCAL_CI_LLVM_HASH="${TASK_LOCAL_CI_LLVM_HASH}"
RUN_BACKEND_STAGES="${TASK_RUN_BACKEND_STAGES:-true}"
BACKEND_SKIP_REASON="${TASK_BACKEND_SKIP_REASON}"
if [[ -n "${TASK_RUN_FLAGGEMS_TESTS}" ]]; then
  RUN_FLAGGEMS_TESTS="${TASK_RUN_FLAGGEMS_TESTS}"
fi
if [[ -n "${TASK_FLAGGEMS_TEST_MODE}" ]]; then
  FLAGGEMS_TEST_MODE="${TASK_FLAGGEMS_TEST_MODE}"
fi
if [[ -n "${TASK_FRONTEND_BUILD_MODE}" ]]; then
  FRONTEND_BUILD_MODE="${TASK_FRONTEND_BUILD_MODE}"
fi
if [[ "${RUN_BACKEND_STAGES}" == "false" ]]; then
  RUN_FLAGGEMS_TESTS="false"
  RUN_COMPILE_BENCHMARK="false"
  RUN_PASS_PROFILE="false"
  RUN_IR_SERIALIZATION_BENCHMARK="false"
  INSTALL_FLAGGEMS_PACKAGES="0"
  EXPECTED_TRITON_BACKEND=""
  BACKEND_PATH=""
  BACKEND_ENVSETUP=""
  BACKEND_ENVSETUP_ARGS=""
  BACKEND_TEST_COMMAND=""
  BACKEND_UNINSTALL_PACKAGES=""
  BACKEND_WHEEL_PATTERN=""
fi

sha="${1:?usage: run_deterministic_ci_in_container.sh <commit-sha> <source-branch>}"
GITEE_BRANCH="${2:?usage: run_deterministic_ci_in_container.sh <commit-sha> <source-branch>}"
if [[ ! "${sha}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "Local CI target SHA must be a lowercase 40-character hexadecimal commit." >&2
  exit 2
fi
PYTHON_BIN="${PYTHON_BIN:-python3}"
LOCAL_CI_CONTAINER="${LOCAL_CI_CONTAINER:-anchor-sophgo-ci-prod}"
CONTAINER_CI_TASK_TMP_ROOT=""
CONTAINER_CI_RUNNER_DIR=""
CONTAINER_TASK_TMP_TOOL=""
LOCAL_CI_CONTAINER_GITEE_USERNAME="${LOCAL_CI_CONTAINER_GITEE_USERNAME:-${GITEE_READ_USERNAME:-${GITEE_USERNAME:-}}}"
LOCAL_CI_CONTAINER_GITEE_TOKEN="${LOCAL_CI_CONTAINER_GITEE_TOKEN:-${GITEE_READ_TOKEN:-}}"
if [[ -z "${LOCAL_CI_CONTAINER_GITEE_TOKEN}" && "${LOCAL_CI_ALLOW_WRITE_TOKEN_IN_CONTAINER:-0}" == "1" ]]; then
  LOCAL_CI_CONTAINER_GITEE_TOKEN="${GITEE_TOKEN:-}"
fi

pass_env=(
  GITEE_REPO_URL GITEE_BRANCH ANCHOR_DIR WORKSPACE
  GITEE_RESULTS_REPO_URL GITEE_RESULTS_BRANCH LOCAL_CI_RUN_ID LOCAL_CI_BASE_SHA LOCAL_CI_BASE_REF
  LOCAL_CI_PROFILE_NAME LOCAL_CI_LLVM_HASH RUN_BACKEND_STAGES BACKEND_SKIP_REASON
  BACKEND_PROFILE EXPECTED_TRITON_BACKEND BACKEND_PATH BACKEND_ENVSETUP BACKEND_ENVSETUP_ARGS BACKEND_TEST_COMMAND BACKEND_UNINSTALL_PACKAGES BACKEND_WHEEL_PATTERN
  RUN_FLAGGEMS_TESTS FLAGGEMS_CLONE_DIR FLAGGEMS_REF FLAGGEMS_PIP_PACKAGES FLAGGEMS_TEST_MODE FLAGGEMS_SAMPLE_SIZE FLAGGEMS_RANDOM_SEED FLAGGEMS_TEST_OP FLAGGEMS_TEST_COMMAND FLAGGEMS_PYTEST_ARGS FLAGGEMS_IDLE_TIMEOUT_SECONDS FLAGGEMS_TOTAL_TIMEOUT_SECONDS FLAGGEMS_FULL_TIMEOUT_EXTENSION_SECONDS FLAGGEMS_FULL_HARD_TIMEOUT_SECONDS FLAGGEMS_CLEAR_CACHE FLAGGEMS_WHITELIST FLAGGEMS_FULL_LIST FLAGGEMS_SELECTED_FILE INSTALL_FLAGGEMS_PACKAGES
  LLVM_BUILD_DIR PPL_ROOT PACKAGE_TOOL PYTHON_BIN PYTHON_VENV_ACTIVATE SOURCE_ENVSETUP FRONTEND_BUILD_MODE FRONTEND_BUILD_COMMAND LOCAL_CI_ARTIFACT_ROOT
  RUN_COMPILE_BENCHMARK COMPILE_BENCHMARK_KERNELS COMPILE_BENCHMARK_REPEAT COMPILE_BENCHMARK_WARMUP
  COMPILE_BENCHMARK_THRESHOLD COMPILE_BENCHMARK_TIMEOUT MAX_JOBS CMAKE_BUILD_PARALLEL_LEVEL NINJAFLAGS UV_LINK_MODE
  RUN_PASS_PROFILE PASS_PROFILE_KERNELS PASS_PROFILE_REPEAT PASS_PROFILE_WARMUP PASS_PROFILE_THRESHOLD
  PASS_PROFILE_MIN_BASE_MS PASS_PROFILE_MIN_DELTA_MS PASS_PROFILE_TIMEOUT
  RUN_IR_SERIALIZATION_BENCHMARK IR_SERIALIZATION_KERNELS IR_SERIALIZATION_REPEAT IR_SERIALIZATION_WARMUP
  IR_SERIALIZATION_METRICS IR_SERIALIZATION_THRESHOLD IR_SERIALIZATION_MIN_BASE_MS
  IR_SERIALIZATION_MIN_DELTA_MS IR_SERIALIZATION_TIMEOUT
)

docker_args=()
for name in "${pass_env[@]}"; do
  if [[ -n "${!name:-}" ]]; then
    docker_args+=(-e "${name}=${!name}")
  fi
done
if [[ -n "${LOCAL_CI_CONTAINER_GITEE_USERNAME}" ]]; then
  docker_args+=(-e "GITEE_USERNAME=${LOCAL_CI_CONTAINER_GITEE_USERNAME}")
fi
if [[ -n "${LOCAL_CI_CONTAINER_GITEE_TOKEN}" ]]; then
  docker_args+=(-e "GITEE_TOKEN=${LOCAL_CI_CONTAINER_GITEE_TOKEN}")
fi

cleanup_container_task_tmp() {
  local status="$?"
  local cleanup_status=0
  trap - EXIT INT TERM
  set +e
  if [[ -n "${CONTAINER_CI_TASK_TMP_ROOT}" && -n "${CONTAINER_TASK_TMP_TOOL}" ]]; then
    docker exec "${LOCAL_CI_CONTAINER}" \
      "${PYTHON_BIN}" "${CONTAINER_TASK_TMP_TOOL}" cleanup \
        --path "${CONTAINER_CI_TASK_TMP_ROOT}" \
        --target-sha "${sha}" || cleanup_status=$?
    if [[ ${cleanup_status} -ne 0 ]]; then
      echo "Failed to clean Local CI task temporary root: ${CONTAINER_CI_TASK_TMP_ROOT}" >&2
      if [[ ${status} -eq 0 ]]; then
        status="${cleanup_status}"
      fi
    fi
  fi
  exit "${status}"
}

trap cleanup_container_task_tmp EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

CONTAINER_CI_TASK_TMP_ROOT="$(
  docker exec "${LOCAL_CI_CONTAINER}" \
    mktemp -d "/tmp/triton-anchor-local-ci-task.${sha:0:12}.XXXXXX"
)"
if [[ ! "${CONTAINER_CI_TASK_TMP_ROOT}" =~ ^/tmp/triton-anchor-local-ci-task\.${sha:0:12}\.[A-Za-z0-9]{6}$ ]]; then
  echo "Container returned an invalid Local CI task temporary root: ${CONTAINER_CI_TASK_TMP_ROOT@Q}" >&2
  exit 1
fi
CONTAINER_CI_RUNNER_DIR="${CONTAINER_CI_TASK_TMP_ROOT}/runner"
CONTAINER_TASK_TMP_TOOL="${CONTAINER_CI_TASK_TMP_ROOT}/task_tmp.py"

docker cp "${LOCAL_CI_ROOT}/shared/task_tmp.py" \
  "${LOCAL_CI_CONTAINER}:${CONTAINER_TASK_TMP_TOOL}"
docker exec "${LOCAL_CI_CONTAINER}" \
  "${PYTHON_BIN}" "${CONTAINER_TASK_TMP_TOOL}" prepare \
    --path "${CONTAINER_CI_TASK_TMP_ROOT}" \
    --target-sha "${sha}"
docker cp "${LOCAL_CI_ROOT}/." "${LOCAL_CI_CONTAINER}:${CONTAINER_CI_RUNNER_DIR}/"

docker exec \
  "${docker_args[@]}" \
  -e LOCAL_CI_COMMIT="${sha}" \
  -e LOCAL_CI_SCRIPT_STAGED="1" \
  -e LOCAL_CI_TASK_TMP_ROOT="${CONTAINER_CI_TASK_TMP_ROOT}" \
  -e LOCAL_CI_RUNNER_DIR="${CONTAINER_CI_RUNNER_DIR}" \
  -e TMPDIR="${CONTAINER_CI_TASK_TMP_ROOT}/tmp" \
  "${LOCAL_CI_CONTAINER}" \
  bash -lc '
    bash "${LOCAL_CI_RUNNER_DIR}/deterministic_ci/run_deterministic_ci.sh" "${LOCAL_CI_COMMIT}"
  '
